<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 4 Correlations | Statistical tests as linear models</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 4 Correlations | Statistical tests as linear models" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Correlations | Statistical tests as linear models" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Steve Doogue">


<meta name="date" content="2019-04-05">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="the-linear-model.html">
<link rel="next" href="appendixtypes.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>2</b> The data</a><ul>
<li class="chapter" data-level="2.1" data-path="data.html"><a href="data.html#samplevalues"><i class="fa fa-check"></i><b>2.1</b> Sample values</a></li>
<li class="chapter" data-level="2.2" data-path="data.html"><a href="data.html#rank_trans"><i class="fa fa-check"></i><b>2.2</b> Rank-transformed values</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-linear-model.html"><a href="the-linear-model.html"><i class="fa fa-check"></i><b>3</b> The linear model</a><ul>
<li class="chapter" data-level="3.1" data-path="the-linear-model.html"><a href="the-linear-model.html#overview-of-the-linear-model"><i class="fa fa-check"></i><b>3.1</b> Overview of the linear model</a></li>
<li class="chapter" data-level="3.2" data-path="the-linear-model.html"><a href="the-linear-model.html#estimating-linear-models-in-r"><i class="fa fa-check"></i><b>3.2</b> Estimating linear models in R</a></li>
<li class="chapter" data-level="3.3" data-path="the-linear-model.html"><a href="the-linear-model.html#assumptions"><i class="fa fa-check"></i><b>3.3</b> Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>4</b> Correlations</a><ul>
<li class="chapter" data-level="4.1" data-path="correlations.html"><a href="correlations.html#pearson-correlation"><i class="fa fa-check"></i><b>4.1</b> Pearson correlation</a></li>
<li class="chapter" data-level="4.2" data-path="correlations.html"><a href="correlations.html#spearman-correlation"><i class="fa fa-check"></i><b>4.2</b> Spearman correlation</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="appendixtypes.html"><a href="appendixtypes.html"><i class="fa fa-check"></i><b>5</b> Appendix - Types of variables</a><ul>
<li class="chapter" data-level="5.1" data-path="appendixtypes.html"><a href="appendixtypes.html#discrete-variables"><i class="fa fa-check"></i><b>5.1</b> Discrete variables</a></li>
<li class="chapter" data-level="5.2" data-path="appendixtypes.html"><a href="appendixtypes.html#continuous-variables"><i class="fa fa-check"></i><b>5.2</b> Continuous variables</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical tests as linear models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="correlations" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Correlations</h1>
<p>Correlation is a measure of the strength and direction of association that exists between two variables. Correlation coefficents (<span class="math inline">\(r\)</span>) assume values in the range from −1 to +1, where ±1 indicates the strongest possible positive or negative correlation and 0 indicates no linear association between the variables.</p>
<div id="pearson-correlation" class="section level2">
<h2><span class="header-section-number">4.1</span> Pearson correlation</h2>
<p>We start by looking at the Pearson correlation coefficient. The following built-in R function can be used to assess the correlation between variables <code>x</code> and <code>y</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(y, x, <span class="dt">method =</span> <span class="st">&quot;pearson&quot;</span>) <span class="co"># Built-in test</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  y and x
## t = -1.6507, df = 48, p-value = 0.1053
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.47920849  0.04978276
## sample estimates:
##        cor 
## -0.2317767</code></pre>
<p>The output shows that the correlation coefficient (<span class="math inline">\(r\)</span>) is -0.2318, with a p-value of 0.1053. On this basis, we would not reject the null hypothesis that the true correlation is equal to 0.</p>
<p>Now we can demonstrate that the linear model gives the exact same t-value and p-value as the Pearson correlation. The equivalent linear model is:</p>
<p><span class="math inline">\(y = \beta_0 + \beta_1x \qquad H_0: \beta_1 = 0\)</span></p>
<p>This model is run in R using the following commands. From the output, we see that the cofficient on <code>x</code>, <span class="math inline">\(\beta_1\)</span>, has a p-value of 0.1053, which is the same as the p-value above.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>x) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summary</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>(<span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ 1 + x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -3.93980 -1.09967  0.12548  1.27904  3.88372 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  0.30000    0.27799  1.0792   0.2859
## x           -0.46355    0.28081 -1.6507   0.1053
## 
## Residual standard error: 1.9657 on 48 degrees of freedom
## Multiple R-squared:  0.05372,    Adjusted R-squared:  0.034006 
## F-statistic:  2.725 on 1 and 48 DF,  p-value: 0.10532</code></pre>
<p>The difference is that the linear model returns the <em>slope</em> of the relationship, <span class="math inline">\(\beta_1\)</span> (which in this case is -0.4636), rather than the correlation coefficient, <span class="math inline">\(r\)</span>. The slope is usually much more interpretable and informative than the correlation coefficient. However it is useful to understand how the two are related, which is by the following formula:</p>
<p><span class="math inline">\(\beta_1 = r * sd_y / sd_x\)</span></p>
<p>This shows that:</p>
<ul>
<li>When both <code>x</code> and <code>y</code> have the same standard deviations (<span class="math inline">\(sd_x\)</span> and <span class="math inline">\(sd_y\)</span>) then the slope (<span class="math inline">\(\beta_1\)</span>) will be equal the correlation coefficient (<span class="math inline">\(r\)</span>)</li>
<li>The ratio of the slope to the correlation coefficient (<span class="math inline">\(\beta_1 / r\)</span>) is equal to the ratio of the standard deviations (<span class="math inline">\(sd_y / sd_x\)</span>). We know that when we set up our data in Section <a href="data.html#samplevalues">2.1</a> that the standard deviation of <code>y</code> was twice as large as <code>x</code>. This is why the value of the slope (-0.4636) is twice the size of the correlation coefficient (-0.2318),</li>
<li>The slope from the linear model will always have the same sign (+ or -) as the correlation coefficient (as standard devaiations are always positive).</li>
</ul>
</div>
<div id="spearman-correlation" class="section level2">
<h2><span class="header-section-number">4.2</span> Spearman correlation</h2>
<p>There will be times when it is more appropriate to use the <strong>Spearman rank correlation</strong> than the Pearson correlation.</p>
<ol style="list-style-type: decimal">
<li>When the relationship between the variables is not linear, i.e. not a straight line;</li>
<li>When your data is not normally distributed;<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></li>
<li>When you data has large outliers; or</li>
<li>When you are working with ordinal rather than continuous data.<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a></li>
</ol>
<p>The Spearman correlation is a <em>non-parameteric</em> test as it does not require that the parameters of the linear model hold true - for example, there does not need to be a linear relationship between the two variables, and the data does not need to be normally distributed.</p>
<p>The Spearman rank correlation is the same as a Pearson correlation but using the <em>rank</em> of the values in our samples.This is an approximation only,</p>
<p>in this case, the rank of values in <code>x</code> and <code>y</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Spearman</span>
<span class="kw">cor.test</span>(y, x, <span class="dt">method =</span> <span class="st">&quot;spearman&quot;</span>)

<span class="co"># Pearson using ranks</span>
<span class="kw">cor.test</span>(<span class="kw">rank</span>(y), <span class="kw">rank</span>(x), <span class="dt">method =</span> <span class="st">&quot;pearson&quot;</span>)

<span class="co"># Linear model using rank</span>
<span class="kw">lm</span>(<span class="kw">rank</span>(y) <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">rank</span>(x)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>(<span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-16">Table 4.1: </span>Here is a nice table!</caption>
<thead>
<tr class="header">
<th align="left">Test</th>
<th align="left">correlation</th>
<th align="left">slope</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">cor.test (Spearman)</td>
<td align="left">-0.2266</td>
<td align="left"></td>
<td align="right">0.1135</td>
</tr>
<tr class="even">
<td align="left">cor.test (Pearson with ranks)</td>
<td align="left">-0.2266</td>
<td align="left"></td>
<td align="right">0.1135</td>
</tr>
<tr class="odd">
<td align="left">lm (with ranks)</td>
<td align="left"></td>
<td align="left">-0.2266</td>
<td align="right">0.1135</td>
</tr>
</tbody>
</table>
<p>Note that we can interpret the slope which is the number of ranks <span class="math inline">\(y\)</span> changes for each rank on <span class="math inline">\(x\)</span>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Technically the variables should have <em>bivariate</em> normality, which means they are normally distrbuted when added together, but this is complex and so it is common just to assess whether the variables are individually normal <a href="https://statistics.laerd.com/spss-tutorials/pearsons-product-moment-correlation-using-spss-statistics.php">(source)</a>. If bivariate normality does not hold then you will still get a fair estimate of <span class="math inline">\(r\)</span>, but the inferential tests (t-statistics and p-values) could be misleading <a href="https://www.researchgate.net/post/Why_should_data_be_normally_distributed_and_continuous_in_order_to_apply_Pearson_correlation">(source)</a>.<a href="correlations.html#fnref1">↩</a></p></li>
<li id="fn2"><p>see Chapter <a href="appendixtypes.html#appendixtypes">5</a> for a description of the different types of data.<a href="correlations.html#fnref2">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="the-linear-model.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendixtypes.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["stat_tests.pdf", "stat_tests.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
